import {useEffect,useState} from 'react'
import {Link,NavLink,Route,Routes} from 'react-router-dom'
import {Activity,ArrowRight,CircleAlert,Copy,KeyRound,RefreshCw,Server,ShieldCheck,Smartphone} from 'lucide-react'
import {ApiError,api,type NodeInfo} from './api'
import {Agreement,Brand,Cabinet,DevicesPage,HelpPage,Landing,SecurityPage,StatusPage} from './CustomerExperience'

type MFAState={enabled:boolean;verified:boolean}

function AdminShell({children}:{children:React.ReactNode}){
  return <div className="app-layout"><aside><Brand/><nav><NavLink to="/app"><Activity/> Кабинет</NavLink><NavLink to="/app/devices"><Smartphone/> Устройства</NavLink><NavLink to="/admin"><Server/> Админ-панель</NavLink></nav><Link className="aside-help" to="/app/help">Помощь</Link></aside><div className="workspace">{children}</div></div>
}

function AdminMFA({state,onVerified}:{state:MFAState;onVerified:()=>void}){
  const [secret,setSecret]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function setup(){setBusy(true);setError('');try{const result=await api<{secret:string}>('/admin/mfa/setup',{method:'POST',body:'{}'});setSecret(result.secret)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function verify(){setBusy(true);setError('');try{await api('/admin/mfa/verify',{method:'POST',body:JSON.stringify({code})});onVerified()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="center-state mfa-state"><ShieldCheck/><small>ЗАЩИТА АДМИН-ПАНЕЛИ</small><h1>Подтвердите второй фактор</h1><p>{state.enabled?'Введите код из приложения-аутентификатора.':'Создайте TOTP-ключ и добавьте его в приложение-аутентификатор. Секрет будет показан один раз.'}</p>{!state.enabled&&!secret&&<button className="primary-action" onClick={setup} disabled={busy}>Создать TOTP <ArrowRight/></button>}{secret&&<div className="mfa-secret"><span>СЕКРЕТ TOTP</span><code>{secret}</code><button onClick={()=>navigator.clipboard.writeText(secret)} aria-label="Скопировать секрет"><Copy/></button></div>}{(state.enabled||secret)&&<div className="mfa-form"><label htmlFor="totp">Код из 6 цифр</label><input id="totp" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button className="primary-action" onClick={verify} disabled={busy||code.length!==6}>Подтвердить <ArrowRight/></button></div>}{error&&<p className="state-error" role="alert">{error}</p>}</div>
}

function Admin(){
  const [overview,setOverview]=useState<Record<string,number>>(),[nodes,setNodes]=useState<NodeInfo[]>([]),[mfa,setMfa]=useState<MFAState>(),[fatalError,setFatalError]=useState<ApiError>(),[enrollmentOpen,setEnrollmentOpen]=useState(false),[bundle,setBundle]=useState(''),[actionError,setActionError]=useState(''),[actionSuccess,setActionSuccess]=useState(''),[enrolling,setEnrolling]=useState(false)
  const load=()=>Promise.all([api<Record<string,number>>('/admin/overview'),api<{items:NodeInfo[]}>('/admin/nodes')]).then(([o,n])=>{setOverview(o);setNodes(n.items)})
  useEffect(()=>{api<MFAState>('/admin/mfa').then(state=>{setMfa(state);if(state.verified)return load()}).catch(e=>setFatalError(e instanceof ApiError?e:new ApiError(0,{title:(e as Error).message})))},[])
  async function enroll(event:React.FormEvent){event.preventDefault();const value=bundle.trim();setActionError('');setActionSuccess('');if(!value.startsWith('rvpn1_')){setActionError('Ключ должен начинаться с rvpn1_. Скопируйте его без пробелов.');return}setEnrolling(true);try{const result=await api<{domain:string}>('/admin/nodes/enroll',{method:'POST',body:JSON.stringify({bundle:value})});setActionSuccess(`Локация ${result.domain} добавлена.`);setBundle('');setEnrollmentOpen(false);try{await load()}catch{setActionError('Локация добавлена, но список не обновился. Нажмите «Обновить».')}}catch(e){if(e instanceof ApiError&&e.status===401)setFatalError(e);else setActionError((e as Error).message)}finally{setEnrolling(false)}}
  if(fatalError?.status===401)return <LoginRequired message={fatalError.message}/>
  if(fatalError)return <AdminFailure message={fatalError.message}/>
  if(!mfa)return <Loading/>
  if(!mfa.verified)return <AdminMFA state={mfa} onVerified={()=>{setMfa({...mfa,verified:true});void load()}}/>
  return <AdminShell><header className="workspace-header"><div><h1>Состояние RiseVPN</h1></div><button className="ghost" onClick={()=>void load()}><RefreshCw/> Обновить</button></header><div className="admin-strip">{[['Аккаунты',overview?.users??'—'],['Активные',overview?.activeSubscriptions??'—'],['Устройства',overview?.devices??'—'],['Узлы в сети',overview?.healthyNodes??'—'],['Уведомления',overview?.activeAlerts??'—']].map(([key,value])=><div key={key}><span>{key}</span><b>{value}</b></div>)}</div><section className="admin-panel"><div className="panel-title"><div><span>ЛОКАЦИИ</span><h2>Узлы сети</h2></div><button onClick={()=>{setEnrollmentOpen(open=>!open);setActionError('');setActionSuccess('')}} aria-expanded={enrollmentOpen} aria-controls="node-enrollment"><Server/> {enrollmentOpen?'Закрыть':'Добавить ключ'}</button></div>{enrollmentOpen&&<form className="enrollment-form" id="node-enrollment" onSubmit={enroll}><label htmlFor="enrollment-bundle">Одноразовый ключ локации</label><textarea id="enrollment-bundle" rows={4} autoFocus spellCheck={false} value={bundle} onChange={event=>setBundle(event.target.value)} placeholder="rvpn1_…" aria-describedby="enrollment-hint"/><div><p id="enrollment-hint">Ключ действует 24 часа и используется один раз. При ошибке введённое значение останется в поле.</p><button type="submit" disabled={enrolling||!bundle.trim()}>{enrolling?'Подключаем…':'Подключить локацию'}</button></div></form>}{actionError&&<div className="operation-message error" role="alert"><CircleAlert/><div><b>{actionSuccess?'Список не обновлён':'Локация не добавлена'}</b><p>{actionError}</p></div></div>}{actionSuccess&&<div className="operation-message success" role="status"><ShieldCheck/><div><b>Готово</b><p>{actionSuccess}</p></div></div>}{nodes.length?<div className="node-table">{nodes.map(node=><div key={node.id}><span className={`status-dot ${node.status}`}/><b>{node.domain}</b><span>{node.status}</span><span>{Math.round(node.loadRatio*100)}% нагрузки</span><button aria-label={`Команды ${node.domain}`}>•••</button></div>)}</div>:<div className="admin-empty"><Server/><h3>Нет подключённых узлов</h3><p>Добавьте одноразовый ключ, полученный после установки локации.</p></div>}</section></AdminShell>
}

function Loading(){return <div className="center-state"><RefreshCw className="spin"/><p>Загружаем данные…</p></div>}
function LoginRequired({message}:{message:string}){return <div className="center-state"><KeyRound/><h1>Нужен вход</h1><p>{message}</p><a className="primary-action" href="/auth/telegram/start">Войти через Telegram</a></div>}
function AdminFailure({message}:{message:string}){return <div className="center-state"><CircleAlert/><h1>Панель недоступна</h1><p>{message}</p><button className="primary-action" onClick={()=>location.reload()}>Повторить загрузку</button></div>}
function PaymentSoon(){return <div className="error-page"><Brand/><div className="error-code">ОПЛАТА</div><h1>Онлайн-оплата скоро появится</h1><p>Пока баланс можно пополнить через поддержку.</p><Link className="primary-action" to="/app/help">Обратиться в поддержку <ArrowRight/></Link></div>}

export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/app" element={<Cabinet/>}/><Route path="/app/devices" element={<DevicesPage/>}/><Route path="/app/security" element={<SecurityPage/>}/><Route path="/app/help" element={<HelpPage/>}/><Route path="/admin/*" element={<Admin/>}/><Route path="/payment" element={<PaymentSoon/>}/><Route path="/agreement" element={<Agreement/>}/><Route path="/status" element={<StatusPage/>}/><Route path="*" element={<PaymentSoon/>}/></Routes>}
