import {useEffect,useMemo,useState} from 'react'
import {Link,NavLink} from 'react-router-dom'
import {Activity,ArrowRight,Check,ChevronRight,Copy,ExternalLink,HelpCircle,KeyRound,LogIn,LogOut,Mail,MessageCircle,Radio,RefreshCw,ShieldCheck,Smartphone,Wallet,Wifi} from 'lucide-react'
import {ApiError,api,formatBytes,formatMoney,logout,type NodeInfo,type Plan} from './api'

export type Me={displayName:string;username:string;balanceKopecks:number;role:string;csrfToken:string;termsAccepted:boolean}
type Subscription={plan:string;status:string;quotaBytes:number;usedBytes:number}
type Device={id:string;slot:number;name:string;bound:boolean;lastSeenAt?:string}

const fallbackPlans:Plan[]=[
  {code:'TRIAL',name:'Trial',priceKopecks:0,deviceLimit:1,quotaBytes:20e9,speedBps:30e6,throttleBps:0,p2pAllowed:false,automaticLocation:true},
  {code:'LITE',name:'Lite',priceKopecks:14900,deviceLimit:1,quotaBytes:150e9,speedBps:50e6,throttleBps:5e6,p2pAllowed:false,automaticLocation:true},
  {code:'PLUS',name:'Plus',priceKopecks:29900,deviceLimit:3,quotaBytes:600e9,speedBps:200e6,throttleBps:10e6,p2pAllowed:true,automaticLocation:true},
  {code:'ULTRA',name:'Ultra',priceKopecks:49900,deviceLimit:7,quotaBytes:2e12,speedBps:0,throttleBps:20e6,p2pAllowed:true,automaticLocation:true},
]

export function Brand(){return <Link className="brand" to="/" aria-label="RiseVPN, на главную"><span>Rise</span>VPN</Link>}

function useMe(){
  const [me,setMe]=useState<Me|null>()
  const [error,setError]=useState('')
  useEffect(()=>{api<Me>('/me').then(setMe).catch(e=>{if(e instanceof ApiError&&e.status===401)setMe(null);else setError((e as Error).message)})},[])
  return {me,setMe,error}
}

function Header({viewer}:{viewer?:Me|null}){
  return <header className="header"><Brand/><nav aria-label="Основная навигация"><a href="/#network">Локации</a><a href="/#plans">Тарифы</a><a href="/#privacy">Приватность</a><a href="/#faq">Вопросы</a></nav>{viewer?<Link className="login" to="/app">Кабинет <Activity size={17}/></Link>:<a className="login" href="/auth/telegram/start">Войти <LogIn size={17}/></a>}</header>
}

function RouteVisual(){
  const routes=[['01','41 мс',118],['02','63 мс',206],['03','28 мс',294],['04','76 мс',382],['05','91 мс',470]]
  return <div className="instrument" aria-label="Иллюстрация выбора подключения"><div className="instrument-bezel" aria-hidden="true"/><div className="instrument-cap"><span>RISEVPN / CONNECTION</span><b>R‑05 / CHECK</b></div><i className="screw screw-a"/><i className="screw screw-b"/><i className="screw screw-c"/><i className="screw screw-d"/><div className="scale scale-left">{['300','200','150','100','50','0'].map(x=><span key={x}>{x}</span>)}</div><div className="stability-scale"><span>STABILITY</span><i/><i/><i/><i/><i/><b>94%</b></div><svg viewBox="0 0 820 560" role="img" aria-label="Проверка пяти подключений и выбор третьего">{routes.map(([id,rtt,y],i)=><g key={id} className={i===2?'route selected':'route'}><text x="34" y={Number(y)+4}>{id}</text><circle cx="90" cy={y} r="7"/><text className="route-rtt" x="110" y={Number(y)+4}>{rtt}</text><path d={`M90 ${y} C 260 ${y}, 390 ${Number(y)+(i-2)*16}, 520 ${305+(i-2)*18} S 625 305, 690 305`}/></g>)}<g className="verified" transform="translate(690 305)"><circle r="49"/><circle r="32"/><path d="M-13 0l9 10 21-24"/><text x="-34" y="78">AUTO / 03</text></g></svg><div className="instrument-result"><span>SELECTED</span><b>ROUTE 03 · 28 MS</b><small>CONNECTION READY</small></div><div className="verification"><ShieldCheck size={20}/> ПОДКЛЮЧЕНИЕ ГОТОВО</div></div>
}

const locations=['Варшава','Франкфурт','Париж','Амстердам','Шарлотт','Вена','Стокгольм','Лондон','Хельсинки']
function LocationRail(){return <section className="network-rail location-rail" id="network"><span className="rail-label"><Radio size={16}/> ЛОКАЦИИ</span><div className="location-list">{locations.map(city=><div className="node-tick" key={city}><span className="status-dot healthy"/><b>{city}</b><small>доступна</small></div>)}</div></section>}

export function Landing(){
  const {me}=useMe()
  const [plans,setPlans]=useState(fallbackPlans)
  useEffect(()=>{api<{items:Plan[]}>('/plans').then(x=>setPlans(x.items)).catch(()=>{})},[])
  const startHref=me?'/app':'/auth/telegram/start'
  return <div><Header viewer={me}/><main><section className="hero"><div className="hero-copy"><h1>VPN без лишних настроек.</h1><p>Войдите через Telegram, добавьте подписку в v2RayTun и подключайтесь. Всё необходимое уже настроено.</p><a className="primary-action" href={startHref}>{me?'Открыть кабинет':'Попробовать бесплатно'} <ArrowRight/></a><span className="trial-note">3 дня бесплатно · до 20 ГБ · без карты</span></div><RouteVisual/></section><LocationRail/><section className="plans-section" id="plans"><div className="section-intro"><h2>Выберите свой тариф</h2><p>Тарифы отличаются скоростью, объёмом трафика, числом устройств и доступом к торрентам.</p></div><div className="plan-table">{plans.map(plan=><article className={plan.code==='PLUS'?'plan featured':'plan'} key={plan.code}><h3>{plan.name}</h3><div className="price">{formatMoney(plan.priceKopecks)}<small>{plan.code==='TRIAL'?' / 3 дня':' / 30 дней'}</small></div><ul><li><Check/> {plan.speedBps?`до ${plan.speedBps/1e6} Мбит/с`:'без ограничения скорости'}</li><li><Check/> {plan.deviceLimit} {plan.deviceLimit===1?'устройство':plan.deviceLimit<5?'устройства':'устройств'}</li><li><Check/> {formatBytes(plan.quotaBytes)} трафика</li><li className={!plan.p2pAllowed?'muted':''}><Check/> {plan.p2pAllowed?'торренты разрешены':'без торрентов'}</li></ul><a href={startHref}>{plan.code==='TRIAL'?'Попробовать':'Выбрать тариф'} <ChevronRight/></a></article>)}</div></section><section className="privacy" id="privacy"><div className="privacy-mark"><ShieldCheck/></div><div><h2>Приватность без сложных слов</h2><p>Мы не сохраняем историю сайтов, адреса посещённых ресурсов и содержимое вашего трафика. Для работы сервиса учитываются только объём трафика, входы в аккаунт и технические ошибки.</p><Link to="/agreement">Подробнее в соглашении <ArrowRight/></Link></div><dl><div><dt>Без истории</dt><dd>не записываем посещённые сайты</dd></div><div><dt>Защищено</dt><dd>секреты подключения хранятся зашифрованными</dd></div><div><dt>Под контролем</dt><dd>устройства видны в личном кабинете</dd></div></dl></section><section className="setup"><h2>Подключение за три шага</h2><ol><li><span>1</span><div><b>Войдите через Telegram</b><p>Отдельный пароль создавать не нужно.</p></div></li><li><span>2</span><div><b>Создайте устройство</b><p>Скопируйте ссылку подписки из кабинета.</p></div></li><li><span>3</span><div><b>Добавьте ссылку в v2RayTun</b><p>После этого можно подключаться.</p></div></li></ol></section><FAQ/></main><Footer/></div>
}

function FAQ(){const items=[['Что понадобится для подключения?','Аккаунт Telegram и приложение v2RayTun. После входа создайте устройство и скопируйте ссылку подписки.'],['Когда начинаются три бесплатных дня?','После первого открытия подписки в v2RayTun. Сам вход в кабинет пробный период не запускает.'],['Что произойдёт после окончания трафика?','На платных тарифах скорость снизится до значения вашего тарифа. Trial отключится после окончания срока или лимита.'],['Можно пользоваться торрентами?','Да, на тарифах Plus и Ultra. На Trial и Lite P2P-трафик ограничен.'],['Как подключить ещё одно устройство?','Создайте отдельный слот в кабинете. Доступное число устройств зависит от тарифа.'],['Где взять ссылку подписки повторно?','Откройте раздел «Устройства» и нажмите «Получить ссылку». Её можно копировать сколько угодно раз.'],['Как оплатить подписку?','Онлайн-оплата пока готовится. По вопросам баланса напишите в поддержку.']];return <section className="faq" id="faq"><h2>Частые вопросы</h2><div>{items.map(([q,a])=><details key={q}><summary>{q}<ChevronRight/></summary><p>{a}</p></details>)}</div></section>}

export function Footer(){return <footer className="site-footer"><Brand/><div className="footer-owner"><b>Басистый Михаил Алексеевич</b><span>ИНН 502920488989 · 2026</span><span className="footer-secure"><ShieldCheck/> Данные подключения защищены шифрованием</span></div><nav><Link to="/agreement">Соглашение</Link></nav></footer>}

function ConsentGate({me,onAccepted}:{me:Me;onAccepted:(me:Me)=>void}){
  const [checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  async function accept(){setBusy(true);setError('');try{await api('/me/accept-terms',{method:'POST',body:'{}'});onAccepted({...me,termsAccepted:true})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="consent-page"><Brand/><div className="consent-panel"><ShieldCheck/><h1>Один шаг до кабинета</h1><p>Прочитайте соглашение и подтвердите, что принимаете условия использования RiseVPN.</p><label className="consent-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>Я прочитал и принимаю <Link to="/agreement" target="_blank">соглашение</Link></span></label><button className="primary-action" disabled={!checked||busy} onClick={accept}>{busy?'Сохраняем…':'Продолжить'} <ArrowRight/></button>{error&&<p className="state-error" role="alert">{error}</p>}</div></div>
}

function AppShell({children,me}:{children:React.ReactNode;me:Me}){return <div className="app-layout"><aside><Brand/><nav><NavLink end to="/app"><Activity/> Обзор</NavLink><NavLink to="/app/devices"><Smartphone/> Устройства</NavLink><NavLink to="/app/security"><KeyRound/> Безопасность</NavLink><NavLink to="/app/help"><HelpCircle/> Помощь</NavLink>{me.role&&<NavLink to="/admin"><Wifi/> Админ-панель</NavLink>}</nav></aside><div className="workspace">{children}</div></div>}

function AccountState({me,error,setMe,children}:{me:Me|null|undefined;error:string;setMe:(me:Me)=>void;children:(me:Me)=>React.ReactNode}){if(error)return <LoginRequired message={error}/>;if(me===null)return <LoginRequired message="Войдите, чтобы открыть кабинет."/>;if(!me)return <Loading/>;if(!me.termsAccepted)return <ConsentGate me={me} onAccepted={setMe}/>;return <>{children(me)}</>}

export function Cabinet(){
  const {me,setMe,error}=useMe(),[sub,setSub]=useState<Subscription>(),[devices,setDevices]=useState<Device[]>([]),[loadError,setLoadError]=useState('')
  useEffect(()=>{if(!me?.termsAccepted)return;Promise.all([api<Subscription>('/subscription'),api<{items:Device[]}>('/devices')]).then(([s,d])=>{setSub(s);setDevices(d.items)}).catch(e=>setLoadError((e as Error).message))},[me?.termsAccepted])
  return <AccountState me={me} setMe={setMe} error={error}>{account=>{if(loadError)return <LoginRequired message={loadError}/>;if(!sub)return <Loading/>;const ratio=Math.min(1,sub.quotaBytes?sub.usedBytes/sub.quotaBytes:0);return <AppShell me={account}><header className="workspace-header"><div><h1>Здравствуйте, {account.displayName}</h1></div><span className="balance"><Wallet/> {formatMoney(account.balanceKopecks)}</span></header>{sub.status==='pending_trial'&&<div className="warning"><ShieldCheck/><div><b>Пробный период ещё не начался</b><p>Создайте устройство и откройте его подписку в v2RayTun.</p></div></div>}<div className="dashboard-grid"><section className="subscription-panel"><div className="panel-head"><span>ТАРИФ</span><b>{sub.plan}</b></div><h2>{sub.status==='pending_trial'?'Можно начинать':sub.status==='active'?'Подключение активно':sub.status}</h2><div className="usage"><div><span>Использовано</span><b>{formatBytes(sub.usedBytes)} / {formatBytes(sub.quotaBytes||20e9)}</b></div><div className="usage-track"><i style={{width:`${ratio*100}%`}}/></div></div><Link className="panel-link" to="/payment">Пополнить баланс <ArrowRight/></Link></section><section className="route-panel"><div className="route-mini"><Wifi/><span className="pulse"/></div><span>АВТОВЫБОР</span><h2>Подберём доступную локацию</h2><p>В подписке всегда остаётся одно готовое подключение.</p></section><section className="devices-panel"><div className="panel-title"><h2>Устройства</h2><Link to="/app/devices">Открыть</Link></div>{devices.length?devices.map(d=><div className="device-row" key={d.id}><Smartphone/><div><b>{d.name}</b><small>{d.bound?'подключено':'ждёт первого подключения'}</small></div><span>{d.bound?'ГОТОВО':'НОВОЕ'}</span></div>):<div className="empty-device"><Smartphone/><p>Устройств пока нет.</p><Link to="/app/devices">Создать устройство</Link></div>}</section><Link className="security-panel" to="/app/security"><ShieldCheck/><div><h2>Безопасность аккаунта</h2><p>Управление входом и активной сессией.</p></div><ArrowRight/></Link></div></AppShell>}}</AccountState>
}

export function DevicesPage(){
  const {me,setMe,error}=useMe(),[devices,setDevices]=useState<Device[]>([]),[name,setName]=useState('Моё устройство'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[links,setLinks]=useState<Record<string,string>>({})
  const load=()=>api<{items:Device[]}>('/devices').then(x=>setDevices(x.items)).catch(e=>setMessage((e as Error).message))
  useEffect(()=>{if(me?.termsAccepted)void load()},[me?.termsAccepted])
  async function create(){setBusy(true);setMessage('');try{const result=await api<{id:string;subscriptionUrl:string}>('/devices',{method:'POST',body:JSON.stringify({name})});setLinks(v=>({...v,[result.id]:result.subscriptionUrl}));await navigator.clipboard.writeText(result.subscriptionUrl).catch(()=>{});setMessage('Устройство создано. Ссылка готова и сохранена ниже.');await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  async function reveal(id:string){setMessage('');try{const result=await api<{subscriptionUrl:string}>(`/devices/${id}/subscription`,{method:'POST',body:'{}'});setLinks(v=>({...v,[id]:result.subscriptionUrl}));await navigator.clipboard.writeText(result.subscriptionUrl).then(()=>setMessage('Ссылка скопирована.')).catch(()=>setMessage('Скопируйте ссылку из поля ниже.'))}catch(e){setMessage((e as Error).message)}}
  return <AccountState me={me} setMe={setMe} error={error}>{account=><AppShell me={account}><header className="workspace-header"><div><h1>Устройства</h1><p>У каждого устройства своя ссылка подписки.</p></div></header><section className="device-manager"><div className="device-create"><label htmlFor="device-name">Название устройства</label><div><input id="device-name" value={name} onChange={e=>setName(e.target.value)} maxLength={80}/><button disabled={busy||!name.trim()} onClick={create}>{busy?'Создаём…':'Создать'}</button></div></div>{message&&<p className="operation-message compact" role="status">{message}</p>}<div className="device-list">{devices.map(device=><article key={device.id}><Smartphone/><div><h2>{device.name}</h2><p>{device.bound?'Подключено':'Ещё не открывалось в приложении'}</p></div><button onClick={()=>void reveal(device.id)}><Copy/> Получить ссылку</button>{links[device.id]&&<div className="subscription-copy"><input value={links[device.id]} readOnly aria-label={`Ссылка подписки для ${device.name}`}/><button onClick={()=>navigator.clipboard.writeText(links[device.id])}><Copy/> Копировать</button></div>}</article>)}</div></section></AppShell>}</AccountState>
}

export function SecurityPage(){const {me,setMe,error}=useMe();async function signOut(){await logout();location.href='/'}return <AccountState me={me} setMe={setMe} error={error}>{account=><AppShell me={account}><header className="workspace-header"><div><h1>Безопасность</h1><p>Вход и защита аккаунта.</p></div></header><section className="security-settings"><div><ShieldCheck/><span><b>Вход через Telegram</b><small>Отдельный пароль RiseVPN не хранится.</small></span><strong>Включено</strong></div><div><KeyRound/><span><b>Соглашение принято</b><small>Доступ к подпискам открыт.</small></span><strong>Готово</strong></div><button className="logout-button" onClick={signOut}><LogOut/> Выйти из аккаунта</button></section></AppShell>}</AccountState>}

export function HelpPage(){const {me,setMe,error}=useMe();return <AccountState me={me} setMe={setMe} error={error}>{account=><AppShell me={account}><header className="workspace-header"><div><h1>Помощь</h1><p>Выберите удобный способ.</p></div></header><div className="help-options"><a href="/#faq"><HelpCircle/><div><h2>Прочитать FAQ</h2><p>Ответы на частые вопросы о подключении и тарифах.</p></div><ArrowRight/></a><a href="mailto:mirrage11@icloud.com"><Mail/><div><h2>Написать на почту</h2><p>Для обычных вопросов и обратной связи.</p></div><ExternalLink/></a><a href="https://t.me/mirragetag" target="_blank" rel="noreferrer"><MessageCircle/><div><h2>Приоритетная поддержка</h2><p>Персональная помощь за дополнительную плату.</p></div><ExternalLink/></a></div></AppShell>}</AccountState>}

export function Agreement(){const {me}=useMe();return <div><Header viewer={me}/><main className="agreement"><h1>Соглашение</h1><p className="agreement-lead">Используя RiseVPN, вы принимаете эти условия.</p><section><h2>1. Аккаунт</h2><p>Вход выполняется через Telegram. Вы отвечаете за доступ к своему аккаунту и не передаёте ссылки подписки посторонним.</p><h2>2. Тариф и Trial</h2><p>Пробный период начинается при первом подключении устройства. Скорость, трафик и число устройств зависят от выбранного тарифа.</p><h2>3. Допустимое использование</h2><p>Сервис нельзя использовать для действий, нарушающих применимое законодательство, работу сети или права других лиц. Доступ может быть ограничен при злоупотреблении.</p><h2>4. Работа сервиса</h2><p>Мы стараемся поддерживать стабильное подключение, но не обещаем непрерывную доступность каждой локации. Технические работы и внешние сбои возможны.</p><h2>5. Данные</h2><p>Мы не сохраняем историю сайтов и содержимое трафика. Технические сведения, необходимые для аккаунта, безопасности и учёта трафика, обрабатываются в объёме, нужном для работы сервиса.</p><h2>6. Поддержка</h2><p>Обычные вопросы можно отправить по электронной почте. Приоритетная персональная поддержка предоставляется отдельно.</p></section><p className="agreement-meta">Редакция от 9 августа 2026 года.</p></main><Footer/></div>}

export function StatusPage(){const {me}=useMe(),[nodes,setNodes]=useState<NodeInfo[]>([]);useEffect(()=>{api<{items:NodeInfo[]}>('/network').then(x=>setNodes(x.items)).catch(()=>{})},[]);const healthy=useMemo(()=>nodes.filter(n=>n.status==='healthy').length,[nodes]);return <div><Header viewer={me}/><main className="agreement"><h1>Статус сети</h1><p className="agreement-lead">{healthy?'Сеть работает штатно.':'Сеть готовится к работе.'}</p><p>Активных узлов: {healthy} из {nodes.length}.</p></main><Footer/></div>}

export function Loading(){return <div className="center-state"><RefreshCw className="spin"/><p>Загружаем данные…</p></div>}
export function LoginRequired({message}:{message:string}){return <div className="center-state"><KeyRound/><h1>Нужен вход</h1><p>{message}</p><a className="primary-action" href="/auth/telegram/start">Войти через Telegram</a></div>}
